### ISSUE TITLE
Problem with building RawVis

### ISSUE THREAD

**Issue by Unn20** [VisualFacts/RawVis#7]
Hi.

I wanted to build up a JAR for RawVis:

Using a command 
`./mvnw -Pprod clean verify`
leads to an error:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< gr.athenarc.imsi.visualfacts.tool:rawvis >--------------
[INFO] Building RawVis 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for gr.athenarc.imsi.visualfacts:rawvis-index:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.963 s
[INFO] Finished at: 2023-01-11T15:12:25+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project rawvis: Could not resolve dependencies for project gr.athenarc.imsi.visualfacts.tool:rawvis:jar:0.0.1-SNAPSHOT: Could not find artifact gr.athenarc.imsi.visualfacts:rawvis-index:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

I have:
 - openjdk version "11.0.17" 2022-10-18
 - Apache Maven 3.6.3

**Comment by stavmars** [comment]
Hi, 
A step is missing from the readme instructions. Thanks for pointing this out.
You should first build the dependency missing, which can be found here:
https://github.com/VisualFacts/rawvis-index

**Comment by Unn20** [comment]
Here is more info from the console (notabene I'm using Ubuntu 20.04):

```
[INFO] > vf-tool@0.0.1-SNAPSHOT jest /home/mleszczyk/Documents/RawVis/RawVis-master
[INFO] > jest --coverage --logHeapUsage --maxWorkers=2 --config src/test/javascript/jest.conf.js
[INFO] 
[INFO] Error: Can't find a root directory while resolving a config file path.
[INFO] Provided path to resolve: src/test/javascript/jest.conf.js
[INFO] cwd: /home/mleszczyk/Documents/RawVis/RawVis-master
[INFO]     at _default (/home/mleszczyk/Documents/RawVis/RawVis-master/node_modules/jest-config/build/resolveConfigPath.js:106:11)
[INFO]     at readConfig (/home/mleszczyk/Documents/RawVis/RawVis-master/node_modules/jest-config/build/index.js:209:49)
[INFO]     at readConfigs (/home/mleszczyk/Documents/RawVis/RawVis-master/node_modules/jest-config/build/index.js:401:32)
[INFO]     at runCLI (/home/mleszczyk/Documents/RawVis/RawVis-master/node_modules/@jest/core/build/cli/index.js:199:29)
[INFO]     at Object.run (/home/mleszczyk/Documents/RawVis/RawVis-master/node_modules/jest/node_modules/jest-cli/build/cli/index.js:173:62)
[INFO]     at Object.<anonymous> (/home/mleszczyk/Documents/RawVis/RawVis-master/node_modules/jest/node_modules/jest-cli/bin/jest.js:16:27)
[INFO]     at Module._compile (internal/modules/cjs/loader.js:1158:30)
[INFO]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
[INFO]     at Module.load (internal/modules/cjs/loader.js:1002:32)
[INFO]     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! vf-tool@0.0.1-SNAPSHOT jest: `jest --coverage --logHeapUsage --maxWorkers=2 --config src/test/javascript/jest.conf.js`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the vf-tool@0.0.1-SNAPSHOT jest script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /home/mleszczyk/.npm/_logs/2023-01-12T13_50_48_352Z-debug.log
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! vf-tool@0.0.1-SNAPSHOT test: `npm run lint && npm run jest`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the vf-tool@0.0.1-SNAPSHOT test script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /home/mleszczyk/.npm/_logs/2023-01-12T13_50_48_369Z-debug.log
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! vf-tool@0.0.1-SNAPSHOT webpack:test: `npm run test`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the vf-tool@0.0.1-SNAPSHOT webpack:test script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /home/mleszczyk/.npm/_logs/2023-01-12T13_50_48_380Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:07 min
[INFO] Finished at: 2023-01-12T14:50:48+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.0:npm (webpack build test) on project rawvis: Failed to run task: 'npm run webpack:test' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by stavmars** [comment]
Can you pull the latest changes and try building it again? It should be ok now.

**Comment by Unn20** [comment]
The build finish with success now. But the application crash during startup:

```
2023-01-13 13:00:36.573  INFO 27356 --- [           main] g.a.imsi.visualfacts.tool.RawVisApp      : The following profiles are active: prod
2023-01-13 13:00:38.691  INFO 27356 --- [           main] g.a.i.v.tool.config.WebConfigurer        : Web application configuration, using profiles: prod
2023-01-13 13:00:38.693  INFO 27356 --- [           main] g.a.i.v.tool.config.WebConfigurer        : Web application fully configured
2023-01-13 13:00:38.758  WARN 27356 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initialDataMigration' defined in URL [jar:file:/home/mleszczyk/Documents/RawVis/RawVis/target/rawvis-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/gr/athenarc/imsi/visualfacts/tool/config/InitialDataMigration.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [gr.athenarc.imsi.visualfacts.tool.config.InitialDataMigration$$EnhancerBySpringCGLIB$$35c3aff1]: Constructor threw exception; nested exception is java.lang.NullPointerException
2023-01-13 13:00:38.774 ERROR 27356 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initialDataMigration' defined in URL [jar:file:/home/mleszczyk/Documents/RawVis/RawVis/target/rawvis-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/gr/athenarc/imsi/visualfacts/tool/config/InitialDataMigration.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [gr.athenarc.imsi.visualfacts.tool.config.InitialDataMigration$$EnhancerBySpringCGLIB$$35c3aff1]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:314)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:295)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at gr.athenarc.imsi.visualfacts.tool.RawVisApp.main(RawVisApp.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [gr.athenarc.imsi.visualfacts.tool.config.InitialDataMigration$$EnhancerBySpringCGLIB$$35c3aff1]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:217)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310)
	... 25 common frames omitted
Caused by: java.lang.NullPointerException: null
	at gr.athenarc.imsi.visualfacts.tool.config.InitialDataMigration.<init>(InitialDataMigration.java:27)
	at gr.athenarc.imsi.visualfacts.tool.config.InitialDataMigration$$EnhancerBySpringCGLIB$$35c3aff1.<init>(<generated>)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204)
	... 27 common frames omitted

```

**Comment by stavmars** [comment]
If you pull the latest changes, the app will start without an error. The problem was that the CSV datasets used are not committed at GitHub, but you can add your own. You need the CSV data file along with a metafile that describes its structure and some parameters of the visualization. 
You can find a sample meta file at [https://github.com/VisualFacts/RawVis/tree/master/src/main/resources/initial-data/taxi.meta.json](https://github.com/VisualFacts/RawVis/tree/master/src/main/resources/initial-data/taxi.meta.json) You also need to specify the data folder you'll use by setting the "workspacePath" option in the "/src/main/resources/initial-data/application.yml" file.
